import { Search, SlidersHorizontal } from 'lucide-react';
import { useMemo, useState } from 'react';
import type { OperatingMode } from '../../config/operatingMode';
import type { ProductAlert, StackItem } from '../../types';
import { affectedComponent } from './FindingCard';
import { EmptyState, PageHeader, StatusBadge } from './ProductUI';

export default function ChangesView({ alerts, stack, mode, onOpen }: { alerts: ProductAlert[]; stack: StackItem[]; mode: OperatingMode; onOpen: (id: string) => void }) {
  const [search, setSearch] = useState(''); const [category, setCategory] = useState('all'); const [status, setStatus] = useState('all'); const [impact, setImpact] = useState('all'); const [sort, setSort] = useState('newest');
  const results = useMemo(() => alerts.filter((item) => (!search || `${item.title} ${item.description}`.toLowerCase().includes(search.toLowerCase())) && (category === 'all' || item.category === category) && (status === 'all' || item.status === status) && (impact === 'all' || item.impact === impact)).sort((a, b) => sort === 'impact' ? b.potentialSavings - a.potentialSavings : sort === 'urgency' ? ['critical','high','medium','low'].indexOf(a.impact) - ['critical','high','medium','low'].indexOf(b.impact) : b.timestamp - a.timestamp), [alerts, search, category, status, impact, sort]);
  const clear = () => { setSearch(''); setCategory('all'); setStatus('all'); setImpact('all'); setSort('newest'); };
  return <div className="product-page"><PageHeader eyebrow="Current-session feed" title="Changes" description="Search and triage findings returned during this browser session. Persistent scan history is not implemented." actions={<StatusBadge tone={mode === 'demo' ? 'yellow' : 'neutral'}>{mode === 'demo' ? 'Demo findings' : `${mode} findings`}</StatusBadge>} />
    <section className="filter-bar" aria-label="Finding filters"><label className="search-field"><span>Search findings</span><div><Search /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search title or evidence" /></div></label><label>Category<select value={category} onChange={(event) => setCategory(event.target.value)}><option value="all">All categories</option><option>FinOps</option><option>DevOps</option><option>Security</option></select></label><label>Impact<select value={impact} onChange={(event) => setImpact(event.target.value)}><option value="all">All impacts</option><option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option></select></label><label>Status<select value={status} onChange={(event) => setStatus(event.target.value)}><option value="all">All statuses</option><option value="active">Needs review</option><option value="resolved">Implemented</option><option value="dismissed">Dismissed</option></select></label><label>Sort<select value={sort} onChange={(event) => setSort(event.target.value)}><option value="newest">Newest</option><option value="urgency">Urgency</option><option value="impact">Projected impact</option></select></label><button className="product-button product-button--quiet" onClick={clear}><SlidersHorizontal /> Clear</button></section>
    <p className="result-count" aria-live="polite">{results.length} result{results.length === 1 ? '' : 's'}</p>
    {results.length ? <div className="changes-list">{results.map((finding) => <button key={finding.id} data-finding-id={finding.id} className="change-row" onClick={() => onOpen(finding.id)}><div><StatusBadge tone="yellow">{finding.category}</StatusBadge>{mode === 'demo' && <StatusBadge>Demo</StatusBadge>}</div><span className="change-title"><strong>{finding.title}</strong><small>{affectedComponent(finding, stack)}</small></span><span><small>Projected impact</small><strong>${finding.potentialSavings.toLocaleString()}/mo</strong></span><span><small>Evidence</small><strong>{mode === 'demo' ? 'Simulated' : 'Unverified'}</strong></span><span><small>Status</small><strong>{finding.status === 'active' ? 'Needs review' : finding.status === 'resolved' ? 'Implemented' : 'Dismissed'}</strong></span></button>)}</div> : <EmptyState title="No matching changes" description={alerts.length ? 'Adjust or clear the filters to see other current-session findings.' : 'Run a scan from Today to create findings. No historical changes are fabricated.'} action={alerts.length ? <button className="product-button product-button--outline" onClick={clear}>Clear filters</button> : undefined} />}
  </div>;
}
