import { ArrowUpRight, CircleDollarSign } from 'lucide-react';
import type { ProductAlert, StackItem } from '../../types';
import { StatusBadge } from './ProductUI';

export function affectedComponent(alert: ProductAlert, stack: StackItem[]) {
  return stack.find((item) => alert.title.toLowerCase().includes(item.name.toLowerCase()))?.name ?? (stack.length === 1 ? stack[0].name : 'Configured stack');
}

export default function FindingCard({ finding, stack, isDemo, primary, onOpen, onImplement, onDismiss }: { finding: ProductAlert; stack: StackItem[]; isDemo: boolean; primary?: boolean; onOpen: () => void; onImplement: () => void; onDismiss: () => void }) {
  const component = affectedComponent(finding, stack);
  return <article className={`finding-card${primary ? ' finding-card--primary' : ''}${finding.status !== 'active' ? ' is-muted' : ''}`}>
    <div className="finding-card-meta"><div><StatusBadge tone="yellow">{finding.category}</StatusBadge>{isDemo && <StatusBadge>Demo finding</StatusBadge>}<StatusBadge tone={finding.status === 'resolved' ? 'green' : 'neutral'}>{finding.status === 'resolved' ? 'Implemented' : finding.status === 'dismissed' ? 'Dismissed' : 'Needs review'}</StatusBadge></div><span>{finding.impact} impact</span></div>
    <div className="finding-card-heading"><div><h2>{finding.title}</h2><span className="finding-component">{component}</span></div><div className="finding-impact"><small>Projected monthly impact</small><strong>${finding.potentialSavings.toLocaleString()}</strong>{isDemo && <em>Demo projection</em>}</div></div>
    <blockquote><span>“</span>{finding.description}</blockquote>
    <div className="finding-source"><span className="finding-source-icon"><ArrowUpRight /></span><div><strong>{isDemo ? 'Example source snapshot' : 'Finding evidence'}</strong><small>{isDemo ? 'Simulated evidence · no official source was scanned' : 'Generated by the latest live analysis'}</small></div></div>
    <div className="finding-actions"><button data-finding-id={finding.id} className="product-button product-button--outline" onClick={onOpen}>Review evidence</button>{finding.status === 'active' && <button className="product-button product-button--dark" onClick={onImplement}><CircleDollarSign /> Mark implemented</button>}{finding.status === 'active' && <button className="product-button product-button--quiet" onClick={onDismiss}>Dismiss</button>}</div>
  </article>;
}
