import { Link } from 'react-router-dom';
import type { OperatingMode } from '../../config/operatingMode';
import { PageHeader, StatusBadge } from './ProductUI';

export default function SettingsView({ mode, onReset }: { mode: OperatingMode; onReset: () => void }) {
  return <div className="product-page"><PageHeader eyebrow="Workspace transparency" title="Settings" description="Only controls supported by the current prototype are shown here." />
    <div className="settings-grid"><section className="settings-card"><p className="product-eyebrow">Workspace</p><h2>Display information</h2><dl><div><dt>Name</dt><dd>{mode === 'demo' ? 'Demo workspace' : 'StackSense workspace'}</dd></div><div><dt>Operating mode</dt><dd><StatusBadge tone={mode === 'demo' ? 'yellow' : mode === 'live' ? 'green' : 'red'}>{mode}</StatusBadge></dd></div><div><dt>Persistence</dt><dd>Stack configuration is stored in this browser. Findings and actions are session-only.</dd></div></dl></section><section className="settings-card"><p className="product-eyebrow">Backend connectivity</p><h2>Request-based status</h2><p>StackSense reports connectivity through scan and report responses. It does not display decorative uptime or unsupported health telemetry.</p><code>{import.meta.env.VITE_API_BASE_URL || 'http://localhost:8787'}</code></section><section className="settings-card"><p className="product-eyebrow">Mode guide</p><h2>What the labels mean</h2><ul><li><strong>Demo:</strong> deterministic fixtures; no official sources queried.</li><li><strong>Live:</strong> backend analysis completed without demo fallback.</li><li><strong>Degraded:</strong> a request failed; existing data remains visible.</li></ul></section><section className="settings-card settings-card--danger"><p className="product-eyebrow">Demo workspace reset</p><h2>Start over</h2><p>Remove the locally saved stack configuration and return to onboarding.</p><button className="product-button product-button--outline" onClick={() => { if (window.confirm('Reset this local StackSense workspace?')) onReset(); }}>Reset workspace</button></section><section className="settings-card"><p className="product-eyebrow">Product limits</p><h2>Current boundaries</h2><p>No authentication, durable finding history, scheduled monitoring, billing, team management, outbound email, or verified-savings workflow is implemented.</p></section><section className="settings-card"><p className="product-eyebrow">Public site</p><h2>Return to the product overview</h2><Link className="product-button product-button--dark" to="/">Open landing page</Link></section></div>
  </div>;
}
