import { lazy, Suspense, useState, type FormEvent } from 'react';
import { Boxes, Network, Pencil, Plus, Trash2 } from 'lucide-react';
import type { StackItem } from '../../types';
import { EmptyState, PageHeader, StatusBadge } from './ProductUI';

const ArchitectureView = lazy(() => import('../ArchitectureView'));

export default function StackView({ stack, pendingRescan, mermaidGraph, onAdd, onUpdate, onRemove, onLoadDemo }: { stack: StackItem[]; pendingRescan: boolean; mermaidGraph: string; onAdd: (name: string, cost: number, category: string) => void; onUpdate: (id: string, updates: Partial<StackItem>) => void; onRemove: (id: string) => void; onLoadDemo: () => void }) {
  const [tab, setTab] = useState<'inventory' | 'architecture'>('inventory');
  const [adding, setAdding] = useState(false);
  const [editing, setEditing] = useState<string | null>(null);
  const [error, setError] = useState('');
  const submitAdd = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); const name = String(data.get('name') ?? '').trim(); const cost = Number(data.get('cost')); const category = String(data.get('category') ?? 'SaaS'); if (!name || !Number.isFinite(cost) || cost < 0) { setError('Enter a component name and a valid monthly cost.'); return; } onAdd(name, cost, category); setAdding(false); setError(''); };
  return <div className="product-page">
    <PageHeader eyebrow="Stack inventory" title="Your stack" description="Configured components determine which findings are relevant. Changes stay local until you run another scan." actions={<><StatusBadge tone={pendingRescan ? 'yellow' : 'neutral'}>{pendingRescan ? 'Rescan required' : 'No pending changes'}</StatusBadge><button className="product-button product-button--dark" onClick={() => { setAdding(true); setTab('inventory'); }}><Plus /> Add component</button></>} />
    <div className="product-segments" role="tablist" aria-label="Stack sections"><button role="tab" aria-selected={tab === 'inventory'} onClick={() => setTab('inventory')}><Boxes /> Inventory</button><button role="tab" aria-selected={tab === 'architecture'} onClick={() => setTab('architecture')}><Network /> Architecture</button></div>
    {tab === 'architecture' ? <section><div className="inferred-note"><strong>Model-inferred architecture</strong><span>This diagram is generated from the configured stack and is not discovered infrastructure.</span></div><Suspense fallback={<div className="product-loading-card">Loading architecture view…</div>}><ArchitectureView mermaidGraph={mermaidGraph} /></Suspense></section> : <>
      {adding && <form className="stack-editor" onSubmit={submitAdd}><label>Product or vendor<input name="name" autoFocus aria-describedby={error ? 'stack-form-error' : undefined} /></label><label>Category<select name="category"><option>SaaS</option><option>API</option><option>Database</option><option>Infrastructure</option></select></label><label>Monthly cost<input name="cost" type="number" min="0" step="1" defaultValue="0" /></label><div><button type="submit" className="product-button product-button--dark">Add component</button><button type="button" className="product-button product-button--quiet" onClick={() => { setAdding(false); setError(''); }}>Cancel</button></div>{error && <p id="stack-form-error" className="field-error">{error}</p>}</form>}
      {stack.length ? <section className="stack-list" aria-label={`${stack.length} configured components`}>{stack.map((item) => <article key={item.id} className="stack-item"><div className="stack-item-mark">{item.name.slice(0, 1).toUpperCase()}</div>{editing === item.id ? <div className="stack-item-edit"><label>Name<input aria-label={`${item.name} name`} value={item.name} onChange={(event) => onUpdate(item.id, { name: event.target.value })} /></label><label>Category<input aria-label={`${item.name} category`} value={item.category} onChange={(event) => onUpdate(item.id, { category: event.target.value })} /></label><label>Monthly cost<input aria-label={`${item.name} monthly cost`} type="number" min="0" value={item.monthlyCost} onChange={(event) => onUpdate(item.id, { monthlyCost: Number(event.target.value) })} /></label></div> : <div className="stack-item-main"><div><h2>{item.name}</h2><span>{item.category}</span></div><dl><div><dt>Monthly cost</dt><dd>${item.monthlyCost.toLocaleString()}</dd></div><div><dt>Monitoring</dt><dd>On request</dd></div><div><dt>Last scan</dt><dd>Session data only</dd></div></dl></div>}<div className="stack-item-actions"><button aria-label={`${editing === item.id ? 'Finish editing' : 'Edit'} ${item.name}`} onClick={() => setEditing(editing === item.id ? null : item.id)}><Pencil /></button><button aria-label={`Remove ${item.name}`} onClick={() => { if (window.confirm(`Remove ${item.name} from this workspace?`)) onRemove(item.id); }}><Trash2 /></button></div></article>)}</section> : <EmptyState title="No stack components" description="Add your first component, or load a clearly labelled example inventory to explore the product." action={<button className="product-button product-button--yellow" onClick={onLoadDemo}>Load demo stack</button>} />}
    </>}
  </div>;
}
