import { useState } from 'react';
import { ArrowLeft, ArrowRight, Check, Plus, Trash2 } from 'lucide-react';
import { Link } from 'react-router-dom';
import type { StackItem, UserContext } from '../types';

export default function Onboarding({ onComplete }: { onComplete: (context: UserContext) => void }) {
  const [step, setStep] = useState(1); const [stack, setStack] = useState<StackItem[]>([]); const [budget, setBudget] = useState(1000); const [focus, setFocus] = useState('Cost efficiency'); const [error, setError] = useState('');
  const update = (id: string, values: Partial<StackItem>) => setStack((items) => items.map((item) => item.id === id ? { ...item, ...values } : item));
  const add = () => setStack((items) => [...items, { id: crypto.randomUUID(), name: '', category: 'SaaS', monthlyCost: 0 }]);
  const demo = () => setStack([{ id: 'demo-api', name: 'Example API', category: 'API', monthlyCost: 500 }, { id: 'demo-database', name: 'Example Database', category: 'Database', monthlyCost: 200 }]);
  const next = () => { if (step === 1 && (!stack.length || stack.some((item) => !item.name.trim()))) { setError('Add at least one named stack component to continue.'); return; } setError(''); setStep((value) => Math.min(value + 1, 4)); };
  return <main className="onboarding-shell"><aside className="onboarding-aside"><Link to="/" className="onboarding-wordmark">STACKSENSE<span>.</span></Link><div><p className="product-eyebrow">Workspace setup</p><h1>Configure what matters.</h1><p>StackSense matches relevant changes to your actual tools and cost assumptions. Nothing is scanned until you request it.</p></div><p className="onboarding-mode"><strong>Demo mode</strong> uses deterministic example findings and never claims that official sources were queried.</p></aside><section className="onboarding-main"><div className="onboarding-top"><Link to="/"><ArrowLeft /> Back to landing</Link><span>Step {step} of 4</span></div><ol className="onboarding-progress" aria-label="Setup progress">{['Stack components','Cost & objective','Review','Enter workspace'].map((label, index) => <li key={label} aria-current={step === index + 1 ? 'step' : undefined} className={step > index + 1 ? 'complete' : ''}><span>{step > index + 1 ? <Check /> : index + 1}</span><em>{label}</em></li>)}</ol><div className="onboarding-content">
    {step === 1 && <><p className="product-eyebrow">01 · Stack components</p><h2>Add the tools you rely on.</h2><p className="onboarding-lead">These components determine which future findings are relevant.</p>{stack.length === 0 && <div className="onboarding-empty"><strong>No components yet</strong><p>Add one manually or load a clearly labelled demo inventory.</p><button className="product-button product-button--yellow" onClick={demo}>Load demo stack</button></div>}<div className="onboarding-stack">{stack.map((item) => <div key={item.id}><label>Product or vendor<input value={item.name} onChange={(event) => update(item.id, { name: event.target.value })} placeholder="Example API" /></label><label>Category<select value={item.category} onChange={(event) => update(item.id, { category: event.target.value })}><option>SaaS</option><option>API</option><option>Database</option><option>Infrastructure</option></select></label><label>Monthly cost<input type="number" min="0" value={item.monthlyCost} onChange={(event) => update(item.id, { monthlyCost: Number(event.target.value) })} /></label><button aria-label={`Remove ${item.name || 'component'}`} onClick={() => setStack((items) => items.filter((entry) => entry.id !== item.id))}><Trash2 /></button></div>)}</div><button className="onboarding-add" onClick={add}><Plus /> Add component</button>{error && <p className="field-error" role="alert">{error}</p>}</>}
    {step === 2 && <><p className="product-eyebrow">02 · Cost &amp; objective</p><h2>Set the business context.</h2><p className="onboarding-lead">These are explicit assumptions—not verified financial data.</p><div className="onboarding-form"><label>Monthly technology budget<input type="number" min="0" value={budget} onChange={(event) => setBudget(Number(event.target.value))} /><span>Used only as workspace context.</span></label><label>Primary objective<select value={focus} onChange={(event) => setFocus(event.target.value)}><option>Cost efficiency</option><option>Reliability</option><option>Security posture</option><option>Engineering velocity</option></select><span>Helps frame recommendations and reports.</span></label></div></>}
    {step === 3 && <><p className="product-eyebrow">03 · Review</p><h2>Check your configuration.</h2><p className="onboarding-lead">You can edit these values later. Stack changes will clearly request a rescan.</p><div className="review-card"><dl><div><dt>Components</dt><dd>{stack.length}</dd></div><div><dt>Recorded monthly spend</dt><dd>${stack.reduce((sum, item) => sum + item.monthlyCost, 0).toLocaleString()}</dd></div><div><dt>Workspace budget</dt><dd>${budget.toLocaleString()}</dd></div><div><dt>Primary objective</dt><dd>{focus}</dd></div></dl><ul>{stack.map((item) => <li key={item.id}><span>{item.name}</span><strong>${item.monthlyCost.toLocaleString()}/mo</strong></li>)}</ul></div></>}
    {step === 4 && <><p className="product-eyebrow">04 · Ready</p><h2>Your workspace is configured.</h2><p className="onboarding-lead">Enter the product to review the stack. A scan runs only when you choose Run scan.</p><div className="onboarding-ready"><span>S.</span><div><strong>Evidence before recommendation.</strong><p>Demo findings will be labelled. Live failures will never be replaced by plausible demo output.</p></div></div></>}
  </div><footer className="onboarding-footer">{step > 1 ? <button className="product-button product-button--quiet" onClick={() => setStep((value) => value - 1)}><ArrowLeft /> Back</button> : <span />}{step < 4 ? <button className="product-button product-button--dark" onClick={next}>Continue <ArrowRight /></button> : <button className="product-button product-button--dark" onClick={() => onComplete({ onboarded: true, stack, monthlyBudget: budget, mainFocus: focus, riskTolerance: 'medium' })}>Enter workspace <ArrowRight /></button>}</footer></section></main>;
}
